import image1 from "./img/product/0027211800_1_2_1.jpg";
import image11 from "./img/product/0027211800_2_1_1.jpg";
import image3 from "./img/product/0144074800_1_1_1.jpg";
import image13 from "./img/product/0144074800_2_1_1.jpg";
import image4 from "./img/product/0364326148_1_1_1.jpg";
import image14 from "./img/product/0364326148_2_1_1.jpg";
import image5 from "./img/product/0364326800_1_1_1.jpg";
import image15 from "./img/product/0364326800_2_1_1.jpg";
import image6 from "./img/product/0365115800_1_2_1.jpg";
import image16 from "./img/product/0365115800_2_1_1.jpg";
import image7 from "./img/product/0907168607_1_1_1.jpg";
import image17 from "./img/product/0907168607_2_1_1.jpg";
import image8 from "./img/product/0915494643_1_1_1.jpg";
import image18 from "./img/product/0915494643_2_1_1.jpg";
import image9 from "./img/product/0931168712_1_1_1.jpg";
import image19 from "./img/product/0931168712_2_1_1.jpg";

const data = {
  products: [
    {
      _id: 1,
      quantity: 20,
      name: "Denim",
      size: 12,
      price: 30,
      type: "Pants",
      gender: "Female",
      image: image1,
      image1: image11,
      sale: true,
      new: false,
      description: "High Riders",
      rating: 5,
      numReviews: 75,
      bin_location: 1,
    },
    {
      _id: 2,
      quantity: 10,
      name: "denim jacket",
      price: 320,
      size: 7,
      type: "jacket",
      gender: "male",
      image: image3,
      image1: image13,
      sale: true,
      new: false,
      description: "short cut",
      rating: 3,
      numReviews: 45,
      bin_location: 2,
    },
    {
      _id: 3,
      quantity: 2,
      name: "t shirt",
      price: 10,
      size: 4,
      type: "shirt",
      gender: "male",
      image: image4,
      image1: image14,
      sale: true,
      new: false,
      description: "nice fit",
      rating: 2,
      numReviews: 20,
      bin_location: 2,
    },
    {
      _id: 4,
      quantity: 2,
      name: "dresses",
      price: 302,
      size: 4,
      type: "shirt",
      gender: "male",
      image: image5,
      image1: image15,
      sale: true,
      new: false,
      description: "short cut",
      rating: 1,
      numReviews: 59,
      bin_location: 2,
    },
    {
      _id: 5,
      quantity: 2,
      name: "shoes",
      price: 150,
      size: 4,
      type: "shirt",
      gender: "male",
      image: image6,
      image1: image16,
      sale: true,
      new: false,
      description: "9in",
      rating: 3.5,
      numReviews: 58,
      bin_location: 2,
    },
    {
      _id: 6,
      quantity: 2,
      name: "hat",
      price: 30,
      size: 4,
      type: "shirt",
      gender: "male",
      image: image7,
      image1: image17,
      sale: true,
      new: false,
      description: "in style",
      rating: 3,
      numReviews: 5,
      bin_location: 2,
    },
    {
      _id: 7,
      quantity: 2,
      name: "sexy wear",
      price: 200,
      size: 4,
      type: "shirt",
      gender: "male",
      image: image8,
      image1: image18,
      sale: true,
      new: false,
      description: "to die for",
      rating: 2,
      numReviews: 8,
      bin_location: 2,
    },
    {
      _id: 8,
      quantity: 2,
      name: "scarf",
      price: 10,
      size: 4,
      type: "shirt",
      gender: "male",
      image: image9,
      image1: image19,
      sale: true,
      new: false,
      description: "matches everything",
      rating: 5,
      numReviews: 19,
      bin_location: 2,
    },
  ],
};

export default data;
