const data = {
  products: [
    {
      _id: 1,
      quantity: 20,
      name: "Denim",
      size: 12,
      price: 30,
      type: "Pants",
      gender: "Female",
      image: "/client/src/img/product/category-jeans-colour-bg-2/jpg",
      sale: true,
      new: false,
      description: "High Riders",
      rating: 5,
      bin_location: 1,
    },
    {
      _id: 2,
      quantity: 10,
      name: "denim jacket",
      price: 320,
      size: 7,
      type: "jacket",
      gender: "male",
      image: "/client/src/img/product/category-jeans-colour-bg-2/jpg",
      sale: true,
      new: false,
      description: "short cut",
      rating: 3,
      bin_location: 2,
    },
    {
      _id: 3,
      quantity: 2,
      name: "t shirt",
      price: 10,
      size: 4,
      type: "shirt",
      gender: "male",
      image: "/client/src/img/product/category-jeans-colour-bg-2/jpg",
      sale: true,
      new: false,
      description: "short cut",
      rating: 3,
      bin_location: 2,
    },
    {
      _id: 4,
      quantity: 2,
      name: "dresses",
      price: 302,
      size: 4,
      type: "shirt",
      gender: "male",
      image: "/client/src/img/product/category-jeans-colour-bg-2/jpg",
      sale: true,
      new: false,
      description: "short cut",
      rating: 3,
      bin_location: 2,
    },
    {
      _id: 5,
      quantity: 2,
      name: "shoes",
      price: 150,
      size: 4,
      type: "shirt",
      gender: "male",
      image: "/client/src/img/product/category-jeans-colour-bg-2/jpg",
      sale: true,
      new: false,
      description: "short cut",
      rating: 3,
      bin_location: 2,
    },
    {
      _id: 6,
      quantity: 2,
      name: "hat",
      price: 30,
      size: 4,
      type: "shirt",
      gender: "male",
      image: "/client/src/img/product/category-jeans-colour-bg-2/jpg",
      sale: true,
      new: false,
      description: "short cut",
      rating: 3,
      bin_location: 2,
    },
    {
      _id: 7,
      quantity: 2,
      name: "sexy wear",
      price: 200,
      size: 4,
      type: "shirt",
      gender: "male",
      image: "/client/src/img/product/category-jeans-colour-bg-2/jpg",
      sale: true,
      new: false,
      description: "short cut",
      rating: 3,
      bin_location: 2,
    },
    {
      _id: 8,
      quantity: 2,
      name: "scarf",
      price: 10,
      size: 4,
      type: "shirt",
      gender: "male",
      image: "/client/src/img/product/category-jeans-colour-bg-2/jpg",
      sale: true,
      new: false,
      description: "short cut",
      rating: 3,
      bin_location: 2,
    },
  ],
};

export default data;